#!/bin/bash
# derive_password
show_usage() {
    echo "Usage: ${0} <salt>"
    echo "Salt must be at least 8 characters long"
    exit 1
}

LENGTH=32

if [ $# -eq 0 ] || [ ${#1} -lt 8 ]; then
    echo "Error: Salt must be provided and at least 8 characters long"
    show_usage
fi

SALT="$1"
read -s -p "Enter Master Passphrase: " MASTER
echo

# Generate base hash
PASSWORD=$(echo -n "$MASTER" | argon2 "$SALT" -id -t 2 -m 16 -p 1 -l "$LENGTH" | grep "Hash:" | awk '{print $2}' | tr -d '\n')
unset MASTER

echo "$PASSWORD"
